/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package racunovodstvo;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.time.Instant;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import static racunovodstvo.Login.dbpassword;
import static racunovodstvo.Login.dburl;
import static racunovodstvo.Login.dbuser;

//import static racunovodstvo.Login.value;

/**
 *
 * @author gogi
 */
public class drzave extends javax.swing.JFrame {

    DefaultTableModel tm;
    int dovoljenjaDodajDrzavo, dovoljenjaSpremeniDrzavo;
    public static Object value;
    public static int staraDrzava=0;
    String opisDrzave, oznakaDrzave, opisDrzaveAN, oznakaDrzaveAN, tekstNapake, naslovNapake;
    int sifraDrzave, sifraDrzaveN, zapst, napaka;
    /**
     * Creates new form drzave
     */
    public drzave() {
        initComponents();
    }
    
        public void populateDrzava(){
        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;        
        ResultSet rs2 = null;        
        PreparedStatement pst2 = null;
        
        //String parrent="a";

        String [] aryNastavitve;
        aryNastavitve=new String[3];
        int i=0;
        
		try (BufferedReader br = new BufferedReader(new FileReader("properties.txt")))//preberi nastavive iz datoteke
		{

			String trenutnaVrstica;

			while ((trenutnaVrstica = br.readLine()) != null) { //preberi nastavitve v tabelo				
                            aryNastavitve[i]=trenutnaVrstica;
                            i++;                            
			}

		} catch (IOException e) {
			e.printStackTrace();
		}
                
                String dburl = aryNastavitve[0];//spremenjivke iz tabele
                String dbuser = aryNastavitve[1];
                String dbpassword = aryNastavitve[2];                

                try {
            con = DriverManager.getConnection(dburl, dbuser, dbpassword);
            pst = con.prepareStatement("SELECT sifraDrzave, kratica, opis FROM drzave");            
            rs = pst.executeQuery();
            pst2 = con.prepareStatement("SELECT spremeniDrzavo FROM dovoljenja WHERE skupina=?");
            pst2.setInt(1, Login.skupina);
            rs2 = pst2.executeQuery();
            
            if (rs2.next()) {           
              dovoljenjaSpremeniDrzavo=rs2.getInt("spremeniDrzavo");
            }
            
        } catch (SQLException ex) {
           // Logger lgr = Logger.getLogger(Version.class.getName());
            //lgr.log(Level.SEVERE, ex.getMessage(), ex);
        }

        try {

            ResultSetMetaData rsmd = rs.getMetaData();
            int columnCount = rsmd.getColumnCount();

            tm = (DefaultTableModel) jTable2.getModel();
            jTable2.setModel(tm);

            jTable2.setRowSelectionAllowed(true);
            tm.setColumnCount(0);

            // add specified columns to table
            for (i = 1; i <= columnCount; i++ ) {
            tm.addColumn(rsmd.getColumnName(i));
            }   

        // clear existing rows
        tm.setRowCount(0);

        // add rows to table
        while (rs.next()) {
            //parrent = rs.getString("konto");
            //osnovna.test.setText(String.valueOf(parrent));
            String[] a = new String[columnCount];
            for(i = 0; i < columnCount; i++) {
                a[i] = rs.getString(i+1);
            }
        tm.addRow(a);
        }
        tm.fireTableDataChanged();

        // Close ResultSet and Statement
        rs.close();
        pst.close();

        } catch (Exception ex) { 
    //JOptionPane.showMessageDialog(this, ex, ex.getMessage(), WIDTH, null);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;   //Disallow the editing of any cell
            }
        };
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spremeniSifraDrzaveTxt = new javax.swing.JTextField();
        spremeniOznakaDrzaveTxt = new javax.swing.JTextField();
        spremeniOpisDrzaveTxt = new javax.swing.JTextField();
        spremeniDrzavoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        populateDrzava();
        jTable2.setModel(tm);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Dodaj državo", jPanel1);

        jLabel1.setText("Šifra države:");

        jLabel2.setText("Oznaka države:");

        jLabel3.setText("Opis države:");

        spremeniSifraDrzaveTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spremeniSifraDrzaveTxtActionPerformed(evt);
            }
        });

        spremeniDrzavoButton.setText("Spremeni državo");
        spremeniDrzavoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spremeniDrzavoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spremeniSifraDrzaveTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(spremeniOznakaDrzaveTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spremeniDrzavoButton))
                    .addComponent(spremeniOpisDrzaveTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spremeniSifraDrzaveTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spremeniDrzavoButton))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spremeniOznakaDrzaveTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spremeniOpisDrzaveTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Spremeni državo", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        if (evt.getClickCount() == 2){
            if(dovoljenjaSpremeniDrzavo==1)
            getValueOfSelectedRow();
            jTabbedPane1.setSelectedIndex(1);
            if(staraDrzava>0)
                {
                    populateSD();
                }
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void spremeniSifraDrzaveTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spremeniSifraDrzaveTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spremeniSifraDrzaveTxtActionPerformed

    private void spremeniDrzavoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spremeniDrzavoButtonActionPerformed
        if (dovoljenjaSpremeniDrzavo==1)
        {
            preberiSpremenljivke();
            preveriSpremenljivke();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Nimate dovoljenja za spremembo države","Spremeni državo - napaka",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_spremeniDrzavoButtonActionPerformed

    public void preberiSpremenljivke()
    {
       opisDrzave=spremeniOpisDrzaveTxt.getText();
       opisDrzaveAN=opisDrzave.replaceAll("[^\\p{L}]]", "");       
       oznakaDrzave=spremeniOznakaDrzaveTxt.getText();
       oznakaDrzaveAN=oznakaDrzave.replaceAll("[^\\p{L}]", "");
       osnovna.test.setText(opisDrzaveAN);
       sifraDrzave=Integer.parseInt(spremeniSifraDrzaveTxt.getText());       
    }
    
    public void preveriSpremenljivke()
    {
        napaka=0;
        
        if(String.valueOf(sifraDrzave)!=null&&!String.valueOf(sifraDrzave).isEmpty()) //preveri, če je vrednost šifre države prazna
        {
            
        }
        else
        {
            napaka=1;            
        }        
        
        if(staraDrzava!=sifraDrzave) //preveri, če je novi konto enak staremu
        {
            Connection con = null; //če novi konto ni enak staremu, preveri, če že obstaja
            PreparedStatement pst = null;
            ResultSet rs = null;
            
            try {
            con = DriverManager.getConnection(dburl, dbuser, dbpassword); 
            pst = con.prepareStatement("SELECT * FROM drzave WHERE sifraDrzave=?");          
            pst.setString(1, String.valueOf(sifraDrzave));                        
            rs=pst.executeQuery();
            if (rs.next()) {           
               napaka=2;
               zapst=rs.getInt("zapst");
               }            
            }            
            catch (SQLException ex)
            {
            }
            finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (pst != null) {
                    pst.close();
                }
                if (con != null) {
                    con.close();
                }
            } 
            catch (SQLException ex) {
                //Logger lgr = Logger.getLogger(Version.class.getName());
                //lgr.log(Level.WARNING, ex.getMessage(), ex);
            }
        }            
        }
        
        if(opisDrzaveAN!=null&&!opisDrzaveAN.isEmpty()) //preveri, če je vrednost opisa prazna
        {
            
        }
        else
        {
            napaka=3;            
        }
        
        if(oznakaDrzaveAN!=null&&!oznakaDrzaveAN.isEmpty()) //preveri, če je vrednost gornje skupine prazna
        {
            
        }
        else
        {
            napaka=4;            
        } 
        
        //osnovna.test.setText(String.valueOf(napaka));
        
        switch (napaka)
        {
            case 1:
                tekstNapake="Šifra države ne sme biti prazna!";
                break;
            case 2:
                tekstNapake="Država že obstaja!";
                break;
            case 3:
                tekstNapake="Vrednost opisa ne sme biti prazna!";
                break;
            case 4:
                tekstNapake="Oznaka države ne sme biti prazna!";
                break;
        }        
        if(napaka==0)
        {
            updateSD();
        }
        else
        {
            naslovNapake="Spremeni državo - napaka";
            kontniNacrt prikazNapake=new kontniNacrt();
            prikazNapake.prikazNapake(tekstNapake, naslovNapake);
        }
    }
    
    public void updateSD()
    {
        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        
        preberiSpremenljivke();
        
        try {
            con = DriverManager.getConnection(dburl, dbuser, dbpassword);
            pst = con.prepareStatement("UPDATE drzave SET kratica=?, opis=?, sifraDrzave=? WHERE zapst=?");
            pst.setString(1, oznakaDrzaveAN);
            pst.setString(2, opisDrzaveAN);
            pst.setInt(3, sifraDrzave);            
            pst.setInt(4, zapst);
            //osnovna.test.setText(String.valueOf(pst));
            String statement=String.valueOf(pst);
            pst.executeUpdate();
            pst = con.prepareStatement("INSERT INTO log"+"(tekst, uporabnik, podrocje, datum) VALUES"+"(?,?,?,?)");
            pst.setString(1, statement);
            pst.setString(2, Login.anUporabnik);
            String podrocje="drzave";
            pst.setString(3, podrocje);
            long zdaj = Instant.now().getEpochSecond();
            pst.setLong(4,zdaj);
            pst.executeUpdate();

        } catch (SQLException ex) {
           // Logger lgr = Logger.getLogger(Version.class.getName());
            //lgr.log(Level.SEVERE, ex.getMessage(), ex);

        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (pst != null) {
                    pst.close();
                }
                if (con != null) {
                    con.close();
                }

            } catch (SQLException ex) {
                //Logger lgr = Logger.getLogger(Version.class.getName());
                //lgr.log(Level.WARNING, ex.getMessage(), ex);
            }
        }
        populateDrzava();
        
    }
    
    public void populateSD()
    {
        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        //geslo1=null;                        

        try {
            con = DriverManager.getConnection(dburl, dbuser, dbpassword); //populate with old values
            pst = con.prepareStatement("SELECT * FROM drzave WHERE sifraDrzave=?");          
            pst.setString(1, String.valueOf(staraDrzava));                        
            rs=pst.executeQuery();
            if (rs.next()) {           
               opisDrzave= rs.getString("opis"); 
               zapst= rs.getInt("zapst");
               oznakaDrzave= rs.getString("kratica");
               sifraDrzave=rs.getInt("sifraDrzave"); 
              
            }
            
            spremeniOpisDrzaveTxt.setText(opisDrzave);
            spremeniOznakaDrzaveTxt.setText(oznakaDrzave);
            spremeniSifraDrzaveTxt.setText(String.valueOf(sifraDrzave));         
            
            
        } catch (SQLException ex) {

        }
        finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (pst != null) {
                    pst.close();
                }
                if (con != null) {
                    con.close();
                }

            } catch (SQLException ex) {
                //Logger lgr = Logger.getLogger(Version.class.getName());
                //lgr.log(Level.WARNING, ex.getMessage(), ex);
            }
        }
    }
    
    public void getValueOfSelectedRow()
    {
        int row = jTable2.getSelectedRow();
        value=jTable2.getValueAt(row, 0);
        staraDrzava=Integer.parseInt(String.valueOf(value));
        //osnovna.test.setText(Login.stariKonto);
        //new spremeniDrzavo().setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(drzave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(drzave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(drzave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(drzave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new drzave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton spremeniDrzavoButton;
    private javax.swing.JTextField spremeniOpisDrzaveTxt;
    private javax.swing.JTextField spremeniOznakaDrzaveTxt;
    private javax.swing.JTextField spremeniSifraDrzaveTxt;
    // End of variables declaration//GEN-END:variables
}
